### ISSUE TITLE
Keypress required on program start

### ISSUE THREAD

**Issue by Golan2072** [makhidkarun/worldgen#5]
When starting worldgen.py you get blank output, and the menu appears only after pressing a key (any key).

**Comment by LeamHall** [comment]
Not seeing it if i run "python worldgen.py" in the worldgen directory, comes right up. Using Python 2.6.6 on CentOS 6.

FYI, I do see:  "NameError: global name 'GetchUnix' is not defined"

**Comment by Golan2072** [comment]
It now appears that the issue was somehow related to certain sessions of the Windows command prompt. Now resolved. I have also resolved the getch() bug.
